export const GET_POSTS_LIST_REQUEST='GET_POSTS_LIST_REQUEST';
export const GET_POSTS_LIST_SUCCESS='GET_POSTS_LIST_SUCCESS';
export const GET_POSTS_LIST_ERROR='GET_POSTS_LIST_ERROR';

export const POST_REQUEST='POST_REQUEST';
export const POST_SUCCESS='POST_SUCCESS';
export const POST_ERROR='POST_ERROR';

export const IMAGE_REQUEST='IMAGE_REQUEST';
export const IMAGE_SUCCESS='IMAGE_SUCCESS';
export const IMAGE_ERROR='IMAGE_ERROR';